input:
    input_file_name: ../o2/output/AnalysisResults_LHC21i3g2.root
    input_trigger_file_name: ../o2/output/AnalysisResults_ppFilter_OCT_apass3_HL.root
  
    table_maker: table-maker-m-c/output
    table_maker_gen_dir: ["MCTruth_muFromJpsi"]
    table_maker_rec_dir: ["Muons_muonQualityCuts_muFromJpsi"]
    table_maker_obj: ["Pt"]
  
    table_reader: analysis-same-event-pairing/output
    table_reader_dir: ["PairsMuonSEPM_mchTrack"]  
    table_reader_obj: ["Mass"]

output:
    output_fig_name: figures/qc/LHC21i3g2
    output_dir_name: output/MC
    output_file_name: LHC21i3g2.root
  