input:
  input_file_name: ../o2/output/AnalysisResults_LHC22d_pass1_muons.root
  input_trigger_file_name: ../o2/output/AnalysisResults_ppFilter_OCT_apass3_HL.root

  table_maker: table-maker/output
  table_maker_dir: ["Muons_mchTrack"]
  table_maker_obj: ["Pt", "Eta", "Phi"]

  table_reader: analysis-same-event-pairing/output
  table_reader_dir: ["PairsMuonSEPM_mchTrack"]  
  table_reader_obj: ["Mass"]

output:
  output_fig_name: figures/qc/LHC22d_apass1
