input:
    input_file_name: ../o2/output/AnalysisResults_TR_LHC22f_apass1_HL_muons.root
  
    input_table_maker_file_name: ../o2/output/AnalysisResults_TR_LHC22f_apass1_HL_muons.root
    table_maker: table-maker/output
    table_maker_dir: ["Muons_mchTrack", "Muons_muonLowPt", "Muons_matchedMchMid"]
    table_maker_obj: ["Pt"]

    input_table_reader_file_name: ../o2/output/AnalysisResults_TR_LHC22f_apass1_HL_muons.root
    table_reader: analysis-same-event-pairing/output
    table_reader_dir: ["PairsMuonSEPM_mchTrack", "PairsMuonSEPM_muonLowPt", "PairsMuonSEPM_matchedMchMid"]
    table_reader_obj: ["Mass"]

output:
    output_fig_name: figures/qc/LHC22f_apass1
    output_dir_name: output/Data
    output_file_name: LHC22f_apass1_muons.root
  