input:
  run_list_file: run_list.txt
  alien_input_path: /alice/sim/2021/LHC21d9m/300333
  macro_to_run: ReadMCJPsi_Grid.C

output:
  output_dir: task_list
  submitted_output_file: submitted_jobs.txt
  terminated_output_file: terminated_jobs.txt
  alien_output_path: .

merging:
  input_path: /home/luca/GITHUB/dq_analysis_utils/grid/script
  input_file_prefix: AliAnalysis_results_
  output_path: /home/luca/GITHUB/dq_analysis_utils/grid/script
  output_file_prefix: AliAnalysis_results_merged
