input:
  run_list_file: run_list.txt
  alien_input_path: /alice/sim/2021/LHC21d9m/300333

output:
  output_dir: task_list
  submitted_output_file: submitted_jobs.txt
  terminated_output_file: terminated_jobs.txt
  alien_output_path: .
