---
inputs:
  #prompt: [/Users/lucamicheletti/cernbox/summer_student_quarkonia_run3/data/MC_prompt_jpsi_update.root]
  #nonprompt: [/Users/lucamicheletti/cernbox/summer_student_quarkonia_run3/data/MC_non_prompt_jpsi_update.root]
  data: [/home/lmichele/GITHUB/dq_analysis_utils/pp_QC/AO2D_LHC23zs.root]

selections: null
